### ISSUE TITLE
[remote_file] sensitive value is exposed during replacement / destroy 

### ISSUE THREAD

**Issue by rmammadli** [tenstad/terraform-provider-remote#41]
### Terraform Version
Terraform Version: v1.1.3 

### Affected Resource(s)
Affected resource:
- remote_file

### Terraform Configuration Files
```hcl
resource "remote_file" "kubeconfig" {
  provider    = remote.server
  path        = var.remotefile_kubeconfig
  content     = rke_cluster.cluster.kube_config_yaml
  permissions = "0644"
}
```

When a path (filename) is updated/changed, result_conn will output sensitive data related to conn.

For example: private_key

```hcl
  # module.rancher.remote_file.kubeconfig_user[0] must be replaced
-/+ resource "remote_file" "kubeconfig_user" {
      ~ id          = "10.x.x.x:ref/kubeconfig_user" -> (known after apply)
      ~ path        = "ref/kubeconfig_user" -> "ref/kubeconfig_" # forces replacement
      ~ result_conn = [
          - {
              - host                = "10.x.x.x"
              - password            = ""
              - port                = 22
              - private_key         = <<-EOT
                    -----BEGIN OPENSSH PRIVATE KEY-----
                   xyz
                   .....
```

### Expected Behavior
Arguments within result_conn should not reveal sensitive values/data.

**Comment by tenstad** [comment]
Thank your for reporting this. The password field is affected as well. As the fields are marked sensitive, I do not see why they would be shown. Might not be possible to make a field within a computed list/object sensitive.

The issue is related to the whole defaulting functionality, where the resource may use the provider's `conn` if not specified within the file resource. I think `result_conn` can be removed, as it does not work quite as intended anyway: https://github.com/tenstad/terraform-provider-remote/issues/13

**Comment by rmammadli** [comment]
@tenstad, thank you for your prompt response.
That would be nice to have ```result_conn```removed without affecting other functionality of resource.
